# Generated by Django 3.0.7 on 2020-07-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arp_kic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arp_log',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arp_kic.Device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arp_kic.Human'),
        ),
    ]
